import { prisma } from "@/lib/prisma";
import { fetchFreshUrls } from "@/lib/sunoapi";
import { sunoCdnAudioUrl } from "@/lib/sunoapi/mappers";
import { logger } from "@/lib/logger";
import { CDN_URL_TTL_MS } from "@/lib/cdn-constants";

/**
 * Minimal song projection needed to refresh its CDN assets. Matches the
 * columns every existing refresh block selects (audio proxy, image proxy,
 * play/refresh routes, cache warmup).
 */
export interface RefreshableSong {
  id: string;
  sunoJobId: string | null;
  sunoAudioId: string | null;
  /**
   * When true the cover was uploaded/generated by the user — the
   * Suno-provided imageUrl must never overwrite it. Omitted/false means the
   * cover is Suno's own and may be healed.
   */
  imageUrlIsCustom?: boolean;
  /**
   * Parent song's sunoJobId. For alternates, the local `sunoJobId` is a
   * clip-UUID, not a real Suno task-id, so record-info lookups must be
   * keyed by the parent's task-id instead.
   */
  parentSunoJobId?: string | null;
}

export interface AssetRefreshDeps {
  resolveApiKey: () => Promise<string | undefined>;
}

export interface RefreshedCdnUrls {
  /** Absent when the caller opted out of the audio heal (healAudio: false). */
  audioUrl?: string;
  /**
   * Absent when Suno returned no image OR the song has a custom cover —
   * callers can use whatever comes back without re-checking the guard.
   */
  imageUrl?: string;
}

export interface AssetRefreshOptions {
  /**
   * Write the audio columns as part of the heal (default true). The image
   * proxy passes false: a cover request must never rewrite audioUrl — the
   * aggregator can hand back the SAME dead tempfile URL and would regress a
   * row already healed to the permanent cdn1 derivation (incident
   * 2026-07-17).
   */
  healAudio?: boolean;
}

/**
 * Refresh a song's CDN URLs from the Suno aggregator and heal the DB row.
 *
 * Owns the shared refresh recipe: task-id resolution (parent's for
 * alternates), the fetchFreshUrls call, and the heal-write of
 * audioUrl/audioUrlExpiresAt plus imageUrl/imageUrlExpiresAt — the image
 * write is guarded by `imageUrlIsCustom` so a custom cover is never
 * overwritten.
 *
 * Never throws. Returns the fresh URLs on success, null when there is no
 * task-id, the aggregator has no audioUrl, or any step fails (logged).
 */
export async function refreshSongCdnUrls(
  song: RefreshableSong,
  deps: AssetRefreshDeps,
  opts: AssetRefreshOptions = {},
): Promise<RefreshedCdnUrls | null> {
  const healAudio = opts.healAudio !== false;
  const refreshTaskId = song.parentSunoJobId ?? song.sunoJobId;
  if (!refreshTaskId) return null;

  try {
    const apiKey = await deps.resolveApiKey();
    const fresh = await fetchFreshUrls(
      refreshTaskId,
      apiKey,
      song.sunoAudioId ?? undefined,
    );
    const expiresAt = new Date(Date.now() + CDN_URL_TTL_MS);
    const freshImageUrl = song.imageUrlIsCustom
      ? undefined
      : fresh?.imageUrl || undefined;

    if (healAudio && !fresh?.audioUrl) {
      logger.warn(
        { songId: song.id, refreshTaskId },
        "asset-refresh: refresh returned no audioUrl",
      );
      return null;
    }
    if (!healAudio && !freshImageUrl) {
      logger.warn(
        { songId: song.id, refreshTaskId },
        "asset-refresh: refresh returned no usable imageUrl",
      );
      return null;
    }

    await prisma.song.update({
      where: { id: song.id },
      data: {
        ...(healAudio && fresh?.audioUrl
          ? { audioUrl: fresh.audioUrl, audioUrlExpiresAt: expiresAt }
          : {}),
        ...(freshImageUrl
          ? { imageUrl: freshImageUrl, imageUrlExpiresAt: expiresAt }
          : {}),
      },
    });

    return {
      ...(healAudio && fresh?.audioUrl ? { audioUrl: fresh.audioUrl } : {}),
      ...(freshImageUrl ? { imageUrl: freshImageUrl } : {}),
    };
  } catch (err) {
    logger.warn({ songId: song.id, refreshTaskId, err }, "asset-refresh: refresh failed");
    return null;
  }
}

export interface DerivedCdnAudio {
  /** The permanent cdn1.suno.ai mp3 URL that answered. */
  url: string;
  /** The successful (`ok`) upstream response; body not yet consumed. */
  response: Response;
}

/**
 * Last resort: Suno's permanent per-clip CDN, derived from the clip id.
 * Aggregator hosts (tempfile.*) expire their files and the aggregator's
 * record-info refresh can return the same dead URL; the cdn1 mp3 outlives
 * both (incident 2026-07-17: 114 songs with dead tempfile URLs, all live on
 * cdn1). On success the row is healed so future requests skip the dead
 * origin; a failed heal write is non-fatal — the audio still streams.
 *
 * Returns null when there is no clip id, `currentUrl` already is the derived
 * URL (nothing new to try), or the derived URL is dead too.
 */
export async function fetchDerivedCdnAudio(
  song: { id: string; sunoAudioId: string | null },
  currentUrl?: string | null,
): Promise<DerivedCdnAudio | null> {
  if (!song.sunoAudioId) return null;
  const derived = sunoCdnAudioUrl(song.sunoAudioId);
  if (derived === currentUrl) return null;

  try {
    const response = await fetch(derived);
    if (!response.ok) return null;
    await prisma.song
      .update({
        where: { id: song.id },
        data: {
          audioUrl: derived,
          audioUrlExpiresAt: new Date(Date.now() + CDN_URL_TTL_MS),
        },
      })
      .catch((err: unknown) => {
        logger.warn({ songId: song.id, err }, "asset-refresh: derived-cdn heal failed");
      });
    return { url: derived, response };
  } catch (err) {
    logger.warn({ songId: song.id, err }, "asset-refresh: derived cdn fetch threw");
    return null;
  }
}
